[project]
name = 'bitcoin_clarity'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []

[contracts.tickets]
path = "contracts/tickets.clar"
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin]
path = "contracts/clarity-bitcoin.clar"
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin-helper]
path = "contracts/clarity-bitcoin-helper.clar"
clarity_version = 2
epoch = 2.1

[contracts.nft_tickets]
path = 'contracts/nft_tickets.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
